ragflow:
  host: 0.0.0.0
  http_port: 9380
mysql:
  name: 'rag_flow'
  user: 'root'
  password: 'infini_rag_flow'
  host: '127.0.0.1'  # 改为 localhost
  port: 5455         # 对应 docker 映射的端口
es:
  hosts: 'http://127.0.0.1:1200'  # ES 映射端口
  username: 'elastic'
  password: 'infini_rag_flow'
redis:
  db: 1
  password: 'infini_rag_flow'
  host: '127.0.0.1:6379'
minio:
  user: 'rag_flow'
  password: 'infini_rag_flow'
  host: '127.0.0.1:9000'